name: Build and push images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  USER: romeronet
  REPOSITORY: base-images

permissions:
  contents: read
  packages: write

jobs:
  build-web-php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [php, nginx-php]
        environment: [dev, prod]

    name: Build ${{ matrix.image }} for ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare QEMU
        uses: docker/setup-qemu-action@v3

      - name: Prepare BuildX
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.image }} - ${{ matrix.environment }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.image }}/${{ matrix.environment }}
          file: ${{ matrix.image }}/${{ matrix.environment }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPOSITORY }}/${{ matrix.image }}-${{ matrix.environment }}:latest

  build-android:
    name: Build Android SDK image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image for Android
        uses: docker/build-push-action@v5
        with:
          context: ./android-sdk
          file: android-sdk/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPOSITORY }}/android-sdk:latest
