name: Build and push images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [php, nginx]
        environment: [dev, prod]

    name: ${{ matrix.image }} - ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Prepare QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Prepare BuildX
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log in to container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.image }} - ${{ matrix.environment }}
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ${{ matrix.image }}/${{ matrix.environment }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ matrix.image }}-${{ matrix.environment }}:latest
